package com.example.vindecoder;

import java.util.HashMap;
import java.util.Map;

public class DataService {
    public static final Map<String, String> MANUFACTURERS = new HashMap<>();
    public static final Map<String, String> COUNTRIES = new HashMap<>();
    public static final Map<Character, String> MODEL_YEARS = new HashMap<>();

    static {
        initManufacturers();
        initModelYears();
        initCountries();
    }

    private static void initCountries() {
        COUNTRIES.put("A[A-H]", "ZA");
        COUNTRIES.put("A[J-N]", "CI");
        COUNTRIES.put("B[A-E]", "AO");
        COUNTRIES.put("B[F-K]", "KE");
        COUNTRIES.put("B[L-R]", "TZ");
        COUNTRIES.put("C[A-E]", "BJ");
        COUNTRIES.put("C[F-K]", "MG");
        COUNTRIES.put("C[L-R]", "TN");
        COUNTRIES.put("D[A-E]", "EG");
        COUNTRIES.put("D[F-K]", "MA");
        COUNTRIES.put("D[L-R]", "ZM");
        COUNTRIES.put("E[A-E]", "ET");
        COUNTRIES.put("E[F-K]", "NZ");
        COUNTRIES.put("F[A-E]", "GH");
        COUNTRIES.put("F[F-K]", "NG");
        COUNTRIES.put("J[A-Z0]", "JP");
        COUNTRIES.put("K[A-E]", "LK");
        COUNTRIES.put("K[F-K]", "IL");
        COUNTRIES.put("K[L-R]", "KR");
        COUNTRIES.put("K[S-Z0]", "KZ");
        COUNTRIES.put("L[A-Z0]", "CN");
        COUNTRIES.put("M[A-E]", "IN");
        COUNTRIES.put("M[F-K]", "ID");
        COUNTRIES.put("M[L-R]", "TH");
        COUNTRIES.put("N[A-E]", "IR");
        COUNTRIES.put("N[F-K]", "PK");
        COUNTRIES.put("N[L-R]", "TR");
        COUNTRIES.put("P[A-E]", "PH");
        COUNTRIES.put("P[F-K]", "SG");
        COUNTRIES.put("P[L-R]", "MY");
        COUNTRIES.put("R[A-E]", "AE");
        COUNTRIES.put("R[F-K]", "TW");
        COUNTRIES.put("R[L-R]", "VN");
        COUNTRIES.put("R[S-Z0]", "SA");
        COUNTRIES.put("S[A-M]", "GB");
        COUNTRIES.put("(S[N-T])|(W[A-Z0])", "DE");
        COUNTRIES.put("S[U-Z]", "PL");
        COUNTRIES.put("S[1-4]", "LV");
        COUNTRIES.put("T[A-H]", "CH");
        COUNTRIES.put("T[J-P]", "CZ");
        COUNTRIES.put("T[R-V]", "HU");
        COUNTRIES.put("T[W-Z0-1]", "PT");
        COUNTRIES.put("U[H-M]", "DK");
        COUNTRIES.put("U[N-T]", "IE");
        COUNTRIES.put("U[U-Z]", "RO");
        COUNTRIES.put("U[5-7]", "SK");
        COUNTRIES.put("V[A-E]", "AT");
        COUNTRIES.put("V[F-R]", "FR");
        COUNTRIES.put("V[S-W]", "ES");
        COUNTRIES.put("V[X-Z0-2]", "RS");
        COUNTRIES.put("V[3-5]", "HR");
        COUNTRIES.put("V[6-Z0]", "EE");
        COUNTRIES.put("X[A-E]", "BG");
        COUNTRIES.put("X[F-K]", "GR");
        COUNTRIES.put("X[L-R]", "NL");
        COUNTRIES.put("(X[S-W])|(X[3-Z0])", "RU");
        COUNTRIES.put("X[X-Z0-2]", "LU");
        COUNTRIES.put("Y[A-E]", "BE");
        COUNTRIES.put("Y[F-K]", "FI");
        COUNTRIES.put("Y[L-R]", "MT");
        COUNTRIES.put("Y[S-W]", "SE");
        COUNTRIES.put("Y[X-Z0-2]", "NO");
        COUNTRIES.put("Y[3-5]", "BY");
        COUNTRIES.put("Y[6-Z0]", "UA");
        COUNTRIES.put("Z[A-R]", "IT");
        COUNTRIES.put("Z[X-Z0-2]", "SI");
        COUNTRIES.put("Z[3-5]", "LT");
        COUNTRIES.put("(1[A-Z0])|(4[A-Z0])|(5[A-Z0])", "US");
        COUNTRIES.put("2[A-Z0]", "CA");
        COUNTRIES.put("3[A-Z0-7]", "MX");
        COUNTRIES.put("3[8-Z0]", "KY");
        COUNTRIES.put("6[A-W]", "AU");
        COUNTRIES.put("7[A-E]", "NZ");
        COUNTRIES.put("8[A-E]", "AR");
        COUNTRIES.put("8[F-K]", "CL");
        COUNTRIES.put("8[L-R]", "EC");
        COUNTRIES.put("8[S-W]", "PE");
        COUNTRIES.put("8[X-Z0-2]", "VE");
        COUNTRIES.put("9[A-E]", "BR");
        COUNTRIES.put("9[F-K]", "CO");
        COUNTRIES.put("9[L-R]", "PY");
        COUNTRIES.put("9[S-W]", "UY");
        COUNTRIES.put("9[X-Z0-2]", "TT");
        COUNTRIES.put("9[3–9]", "BR");
    }

    private static void initModelYears() {
        MODEL_YEARS.put('0', "2000");
        MODEL_YEARS.put('1', "2001");
        MODEL_YEARS.put('2', "2002");
        MODEL_YEARS.put('3', "2003");
        MODEL_YEARS.put('4', "2004");
        MODEL_YEARS.put('5', "2005");
        MODEL_YEARS.put('6', "2006");
        MODEL_YEARS.put('7', "2007");
        MODEL_YEARS.put('8', "2008");
        MODEL_YEARS.put('9', "2009");
        MODEL_YEARS.put('A', "2010");
        MODEL_YEARS.put('B', "2011");
        MODEL_YEARS.put('C', "2012");
        MODEL_YEARS.put('D', "2013");
        MODEL_YEARS.put('E', "2014");
        MODEL_YEARS.put('F', "2015");
        MODEL_YEARS.put('G', "2016");
        MODEL_YEARS.put('H', "2017");
        MODEL_YEARS.put('J', "2018");
        MODEL_YEARS.put('K', "2019");
        MODEL_YEARS.put('L', "2020");
        MODEL_YEARS.put('M', "2021");
        MODEL_YEARS.put('N', "2022");
        MODEL_YEARS.put('P', "2023");
        MODEL_YEARS.put('R', "2024");
        MODEL_YEARS.put('S', "2025");
        MODEL_YEARS.put('T', "2026");
        MODEL_YEARS.put('V', "2027");
        MODEL_YEARS.put('W', "2028");
        MODEL_YEARS.put('X', "2029");
        MODEL_YEARS.put('Y', "2030");
    }

    private static void initManufacturers() {
        MANUFACTURERS.put("AAV","Volkswagen");
        MANUFACTURERS.put("AC5", "Hyundai");
        MANUFACTURERS.put("ADD","Hyundai");
        MANUFACTURERS.put("AFA","Ford");
        MANUFACTURERS.put("AHT","Toyota");
        MANUFACTURERS.put("JA3","Mitsubishi");
        MANUFACTURERS.put("JA4","Mitsubishi");
        MANUFACTURERS.put("JA","Isuzu");
        MANUFACTURERS.put("JD","Daihatsu");
        MANUFACTURERS.put("JF","Fuji Heavy Industries (Subaru)");
        MANUFACTURERS.put("JH","Honda");
        MANUFACTURERS.put("JK","Kawasaki (motorcycles)");
        MANUFACTURERS.put("JL5","Mitsubishi Fuso");
        MANUFACTURERS.put("JMB","Mitsubishi Motors");
        MANUFACTURERS.put("JMY","Mitsubishi Motors");
        MANUFACTURERS.put("JMZ","Mazda");
        MANUFACTURERS.put("JN","Nissan");
        MANUFACTURERS.put("JS","Suzuki");
        MANUFACTURERS.put("JT","Toyota");
        MANUFACTURERS.put("JY","Yamaha (motorcycles)");
        MANUFACTURERS.put("KL","Daewoo General Motors");
        MANUFACTURERS.put("KM","Hyundai");
        MANUFACTURERS.put("KMY","Daelim (motorcycles)");
        MANUFACTURERS.put("KM1","Hyosung (motorcycles)");
        MANUFACTURERS.put("KN","Kia");
        MANUFACTURERS.put("KNM","Renault Samsung");
        MANUFACTURERS.put("KPA","SsangYong");
        MANUFACTURERS.put("KPT","SsangYong");
        MANUFACTURERS.put("LAE","Jinan Qingqi Motorcycle");
        MANUFACTURERS.put("LAN","Changzhou Yamasaki Motorcycle");
        MANUFACTURERS.put("LBB","Zhejiang Qianjiang Motorcycle (Keeway/Generic)");
        MANUFACTURERS.put("LBE","Beijing Hyundai");
        MANUFACTURERS.put("LBM","Zongshen Piaggio");
        MANUFACTURERS.put("LBP","Chongqing Jainshe Yamaha (motorcycles)");
        MANUFACTURERS.put("LB2","Geely Motorcycles");
        MANUFACTURERS.put("LCE","Hangzhou Chunfeng Motorcycles (CFMOTO)");
        MANUFACTURERS.put("LDC","Dong Feng Peugeot Citroen (DPCA)");
        MANUFACTURERS.put("LDD","Dandong Huanghai Automobile");
        MANUFACTURERS.put("LDN","SouEast Motor");
        MANUFACTURERS.put("LDY","Zhongtong Coach");
        MANUFACTURERS.put("LET","Jiangling-Isuzu Motors");
        MANUFACTURERS.put("LE4","Beijing Benz");
        MANUFACTURERS.put("LFB","FAW (busses)");
        MANUFACTURERS.put("LFG","Taizhou Chuanl Motorcycle Manufacturing");
        MANUFACTURERS.put("LFP","FAW (passenger vehicles)");
        MANUFACTURERS.put("LFT","FAW (trailers)");
        MANUFACTURERS.put("LFV","FAW-Volkswagen");
        MANUFACTURERS.put("LFW","FAW JieFang");
        MANUFACTURERS.put("LFY","Changshu Light Motorcycle Factory");
        MANUFACTURERS.put("LGB","Dong Feng (DFM)");
        MANUFACTURERS.put("LGH","Qoros (formerly Dong Feng (DFM))");
        MANUFACTURERS.put("LGX","BYD Auto");
        MANUFACTURERS.put("LHB","Beijing Automotive Industry Holding");
        MANUFACTURERS.put("LH1","FAW-Haima");
        MANUFACTURERS.put("LJC","JAC");
        MANUFACTURERS.put("LJ1","JAC");
        MANUFACTURERS.put("LKL","Suzhou King Long");
        MANUFACTURERS.put("LL6","Hunan Changfeng Manufacture Joint-Stock");
        MANUFACTURERS.put("LL8","Linhai (ATV)");
        MANUFACTURERS.put("LMC","Suzuki Hong Kong (motorcycles)");
        MANUFACTURERS.put("LPR","Yamaha Hong Kong (motorcycles)");
        MANUFACTURERS.put("LSG","SAIC General Motors");
        MANUFACTURERS.put("LSJ","SAIC MG");
        MANUFACTURERS.put("LSV","SAIC Volkswagen");
        MANUFACTURERS.put("LSY","Brilliance Zhonghua");
        MANUFACTURERS.put("LTV","Toyota Tian Jin");
        MANUFACTURERS.put("LUC","Guangqi Honda");
        MANUFACTURERS.put("LVS","Ford Chang An");
        MANUFACTURERS.put("LVV","Chery");
        MANUFACTURERS.put("LVZ","Dong Feng Sokon Motor Company (DFSK)");
        MANUFACTURERS.put("LZM","MAN");
        MANUFACTURERS.put("LZE","Isuzu Guangzhou");
        MANUFACTURERS.put("LZG","Shaanxi Automobile Group");
        MANUFACTURERS.put("LZP","Zhongshan Guochi Motorcycle (Baotian)");
        MANUFACTURERS.put("LZY","Yutong Zhengzhou");
        MANUFACTURERS.put("LZZ","Chongqing Shuangzing Mech & Elec (Howo)");
        MANUFACTURERS.put("L4B","Xingyue Group (motorcycles)");
        MANUFACTURERS.put("L5C","KangDi (ATV)");
        MANUFACTURERS.put("L5K","Zhejiang Yongkang Easy Vehicle");
        MANUFACTURERS.put("L5N","Zhejiang Taotao (ATV & motorcycles)");
        MANUFACTURERS.put("L5Y","Merato Motorcycle Taizhou Zhongneng");
        MANUFACTURERS.put("L85","Zhejiang Yongkang Huabao Electric Appliance");
        MANUFACTURERS.put("L8X","Zhejiang Summit Huawin Motorcycle");
        MANUFACTURERS.put("MAB","Mahindra & Mahindra");
        MANUFACTURERS.put("MAC","Mahindra & Mahindra");
        MANUFACTURERS.put("MAJ","Ford");
        MANUFACTURERS.put("MAK","Honda Siel Cars");
        MANUFACTURERS.put("MAL","Hyundai");
        MANUFACTURERS.put("MAT","Tata Motors");
        MANUFACTURERS.put("MA1","Mahindra & Mahindra");
        MANUFACTURERS.put("MA3","Suzuki (Maruti)");
        MANUFACTURERS.put("MA6","GM");
        MANUFACTURERS.put("MA7","Mitsubishi (formerly Honda)");
        MANUFACTURERS.put("MBH","Suzuki (Maruti)");
        MANUFACTURERS.put("MBJ","Toyota");
        MANUFACTURERS.put("MBR","Mercedes-Benz");
        MANUFACTURERS.put("MB1","Ashok Leyland");
        MANUFACTURERS.put("MCA","Fiat");
        MANUFACTURERS.put("MCB","GM");
        MANUFACTURERS.put("MC2","Volvo Eicher commercial vehicles limited.");
        MANUFACTURERS.put("MDH","Nissan");
        MANUFACTURERS.put("MD2","Bajaj Auto");
        MANUFACTURERS.put("MD9","Shuttle Cars");
        MANUFACTURERS.put("MEE","Renault");
        MANUFACTURERS.put("MEX","Volkswagen");
        MANUFACTURERS.put("MHF","Toyota");
        MANUFACTURERS.put("MHR","Honda");
        MANUFACTURERS.put("MLC","Suzuki");
        MANUFACTURERS.put("MLH","Honda");
        MANUFACTURERS.put("MMB","Mitsubishi");
        MANUFACTURERS.put("MMC","Mitsubishi");
        MANUFACTURERS.put("MMM","Chevrolet");
        MANUFACTURERS.put("MMS","Suzuki");
        MANUFACTURERS.put("MMT","Mitsubishi");
        MANUFACTURERS.put("MM8","Mazda");
        MANUFACTURERS.put("MNB","Ford");
        MANUFACTURERS.put("MNT","Nissan");
        MANUFACTURERS.put("MPA","Isuzu");
        MANUFACTURERS.put("MP1","Isuzu");
        MANUFACTURERS.put("MRH","Honda");
        MANUFACTURERS.put("MR0","Toyota");
        MANUFACTURERS.put("MS0","KIA");
        MANUFACTURERS.put("MS3","Suzuki Motor Co., Ltd.");
        MANUFACTURERS.put("NLA","Honda");
        MANUFACTURERS.put("NLE","Mercedes-Benz Truck");
        MANUFACTURERS.put("NLH","Hyundai Assan");
        MANUFACTURERS.put("NLT","TEMSA");
        MANUFACTURERS.put("NMB","Mercedes-Benz Buses");
        MANUFACTURERS.put("NMC","BMC");
        MANUFACTURERS.put("NM0","Ford");
        MANUFACTURERS.put("NM4","Tofaş");
        MANUFACTURERS.put("NMT","Toyota");
        MANUFACTURERS.put("NNA","Isuzu");
        MANUFACTURERS.put("PE1","Ford");
        MANUFACTURERS.put("PE3","Mazda");
        MANUFACTURERS.put("PL1","Proton");
        MANUFACTURERS.put("PNA","NAZA (Peugeot)");
        MANUFACTURERS.put("R1N","NIU");
        MANUFACTURERS.put("RA1","Steyr Trucks International FZE");
        MANUFACTURERS.put("RFB","Kymco");
        MANUFACTURERS.put("RFG","Sanyang SYM");
        MANUFACTURERS.put("RFL","Adly");
        MANUFACTURERS.put("RFT","CPI");
        MANUFACTURERS.put("RF3","Aeon Motor");
        MANUFACTURERS.put("RL0","Ford");
        MANUFACTURERS.put("RL1","Suzuki");
        MANUFACTURERS.put("RL2","Ford");
        MANUFACTURERS.put("RL3","Ford");
        MANUFACTURERS.put("RL4","Toyota");
        MANUFACTURERS.put("RL5","Lifan");
        MANUFACTURERS.put("RL6","Piaggio");
        MANUFACTURERS.put("RL8","Lifan");
        MANUFACTURERS.put("RLA","Mitsubishi");
        MANUFACTURERS.put("RLC","Yamaha");
        MANUFACTURERS.put("RLD","Isuzu");
        MANUFACTURERS.put("RLE","Isuzu");
        MANUFACTURERS.put("RLF","BMW");
        MANUFACTURERS.put("RLG","SYM");
        MANUFACTURERS.put("RLH","Honda");
        MANUFACTURERS.put("RLM","Mercedes-Benz");
        MANUFACTURERS.put("RLS","Suzuki");
        MANUFACTURERS.put("RP8","Piaggio");
        MANUFACTURERS.put("SAD","Jaguar (F-Pace)");
        MANUFACTURERS.put("SAL","Land Rover");
        MANUFACTURERS.put("SAJ","Jaguar");
        MANUFACTURERS.put("SAR","Rover");
        MANUFACTURERS.put("SB1","Toyota");
        MANUFACTURERS.put("SBM","McLaren");
        MANUFACTURERS.put("SCA","Rolls Royce");
        MANUFACTURERS.put("SCB","Bentley");
        MANUFACTURERS.put("SCC","Lotus Cars");
        MANUFACTURERS.put("SCE","DeLorean Motor Cars N. Ireland");
        MANUFACTURERS.put("SCF","Aston");
        MANUFACTURERS.put("SDB","Peugeot (formerly Talbot)");
        MANUFACTURERS.put("SED","General Motors Luton Plant");
        MANUFACTURERS.put("SEY","LDV");
        MANUFACTURERS.put("SFA","Ford");
        MANUFACTURERS.put("SFD","Alexander Dennis");
        MANUFACTURERS.put("SHH","Honda");
        MANUFACTURERS.put("SHS","Honda");
        MANUFACTURERS.put("SJN","Nissan");
        MANUFACTURERS.put("SKF","Vauxhall");
        MANUFACTURERS.put("SLP","JCB Research");
        MANUFACTURERS.put("SMT","Triumph Motorcycles");
        MANUFACTURERS.put("SUF","Fiat Auto");
        MANUFACTURERS.put("SUL","FSC");
        MANUFACTURERS.put("SUP","FSO-Daewoo");
        MANUFACTURERS.put("SUU","Solaris Bus & Coach");
        MANUFACTURERS.put("SWV","TA-NO");
        MANUFACTURERS.put("TCC","Micro Compact Car AG (smart 1998-1999)");
        MANUFACTURERS.put("TDM","QUANTYA Swiss Electric Movement");
        MANUFACTURERS.put("TK9","SOR buses");
        MANUFACTURERS.put("TMA","Hyundai Motor Manufacturing");
        MANUFACTURERS.put("TMB","Škoda");
        MANUFACTURERS.put("TMK","Karosa");
        MANUFACTURERS.put("TMP","Škoda trolleybuses");
        MANUFACTURERS.put("TMT","Tatra");
        MANUFACTURERS.put("TM9","Škoda trolleybuses");
        MANUFACTURERS.put("TNE","TAZ");
        MANUFACTURERS.put("TN9","Karosa");
        MANUFACTURERS.put("TRA","Ikarus Bus");
        MANUFACTURERS.put("TRU","Audi");
        MANUFACTURERS.put("TSE","Ikarus Egyedi Autobuszgyar");
        MANUFACTURERS.put("TSM","Suzuki");
        MANUFACTURERS.put("TW1","Toyota Caetano");
        MANUFACTURERS.put("TYA","Mitsubishi Trucks");
        MANUFACTURERS.put("TYB","Mitsubishi Trucks");
        MANUFACTURERS.put("UU1","Renault Dacia");
        MANUFACTURERS.put("UU3","ARO");
        MANUFACTURERS.put("UU6","Daewoo");
        MANUFACTURERS.put("U5Y","Kia Motors");
        MANUFACTURERS.put("U6Y","Kia Motors");
        MANUFACTURERS.put("VAG","Magna Steyr Puch");
        MANUFACTURERS.put("VAN","MAN");
        MANUFACTURERS.put("VBK","KTM (Motorcycles)");
        MANUFACTURERS.put("VF1","Renault");
        MANUFACTURERS.put("VF2","Renault");
        MANUFACTURERS.put("VF3","Peugeot");
        MANUFACTURERS.put("VF4","Talbot");
        MANUFACTURERS.put("VF6","Renault (Trucks & Buses)");
        MANUFACTURERS.put("VF7","Citroën");
        MANUFACTURERS.put("VF8","Matra");
        MANUFACTURERS.put("VF9","Bugatti");
        MANUFACTURERS.put("795","Bugatti");
        MANUFACTURERS.put("VG5","MBK (motorcycles)");
        MANUFACTURERS.put("VLU","Scania");
        MANUFACTURERS.put("VN1","SOVAB");
        MANUFACTURERS.put("VNE","Irisbus");
        MANUFACTURERS.put("VNK","Toyota");
        MANUFACTURERS.put("VNV","Renault-Nissan");
        MANUFACTURERS.put("VSA","Mercedes-Benz");
        MANUFACTURERS.put("VSE","Suzuki (Santana Motors)");
        MANUFACTURERS.put("VSK","Nissan");
        MANUFACTURERS.put("VSS","SEAT");
        MANUFACTURERS.put("VSX","Opel");
        MANUFACTURERS.put("VS6","Ford");
        MANUFACTURERS.put("VS7","Citroën");
        MANUFACTURERS.put("VS9","Carrocerias Ayats");
        MANUFACTURERS.put("VTH","Derbi (motorcycles)");
        MANUFACTURERS.put("VTL","Yamaha (motorcycles)");
        MANUFACTURERS.put("VTT","Suzuki (motorcycles)");
        MANUFACTURERS.put("VV9","TAURO");
        MANUFACTURERS.put("VWA","Nissan");
        MANUFACTURERS.put("VWV","Volkswagen");
        MANUFACTURERS.put("VX1","Zastava / Yugo Serbia");
        MANUFACTURERS.put("WAG","Neoplan");
        MANUFACTURERS.put("WAU","Audi");
        MANUFACTURERS.put("WA1","Audi SUV");
        MANUFACTURERS.put("WBA","BMW");
        MANUFACTURERS.put("WBS","BMW M");
        MANUFACTURERS.put("WBW","BMW");
        MANUFACTURERS.put("WBY","BMW");
        MANUFACTURERS.put("WDA","Daimler");
        MANUFACTURERS.put("WDB","Mercedes-Benz");
        MANUFACTURERS.put("WDC","DaimlerChrysler");
        MANUFACTURERS.put("WDD","Mercedes-Benz");
        MANUFACTURERS.put("WDF","Mercedes-Benz (commercial vehicles)");
        MANUFACTURERS.put("WEB","Evobus GmbH (Mercedes-Bus)");
        MANUFACTURERS.put("WJM","Iveco Magirus");
        MANUFACTURERS.put("WF0","Ford");
        MANUFACTURERS.put("WKE","Fahrzeugwerk Bernard Krone GmbH & Co. KG");
        MANUFACTURERS.put("WKK","Kässbohrer/Setra");
        MANUFACTURERS.put("WMA","MAN");
        MANUFACTURERS.put("WME","smart");
        MANUFACTURERS.put("WMW","MINI");
        MANUFACTURERS.put("WMX","Mercedes-AMG");
        MANUFACTURERS.put("WP0","Porsche");
        MANUFACTURERS.put("WP1","Porsche SUV");
        MANUFACTURERS.put("W09","RUF");
        MANUFACTURERS.put("W0L","Opel");
        MANUFACTURERS.put("W0V","Opel");
        MANUFACTURERS.put("WUA","quattro GmbH");
        MANUFACTURERS.put("WVG","Volkswagen MPV/SUV");
        MANUFACTURERS.put("WVW","Volkswagen");
        MANUFACTURERS.put("WV1","Volkswagen Commercial Vehicles");
        MANUFACTURERS.put("WV2","Volkswagen Bus/Van");
        MANUFACTURERS.put("WV3","Volkswagen Trucks");
        MANUFACTURERS.put("XLB","Volvo (NedCar)");
        MANUFACTURERS.put("XLE","Scania");
        MANUFACTURERS.put("XLR","DAF (trucks)");
        MANUFACTURERS.put("XL9","Spyker");
        MANUFACTURERS.put("363","Spyker");
        MANUFACTURERS.put("XMC","Mitsubishi (NedCar)");
        MANUFACTURERS.put("XTA","Lada/AvtoVAZ");
        MANUFACTURERS.put("XTC","KAMAZ");
        MANUFACTURERS.put("XTH","GAZ");
        MANUFACTURERS.put("XTT","UAZ/Sollers");
        MANUFACTURERS.put("XTY","LiAZ");
        MANUFACTURERS.put("XUF","General Motors");
        MANUFACTURERS.put("XUU","AvtoTor (General Motors SKD)");
        MANUFACTURERS.put("XW8","Volkswagen Group");
        MANUFACTURERS.put("XWB","UZ-Daewoo");
        MANUFACTURERS.put("XWE","AvtoTor (Hyundai-Kia SKD)");
        MANUFACTURERS.put("X1M","PAZ");
        MANUFACTURERS.put("X4X","AvtoTor (BMW SKD)");
        MANUFACTURERS.put("X7L","Renault AvtoFramos");
        MANUFACTURERS.put("X7M","Hyundai TagAZ");
        MANUFACTURERS.put("YBW","Volkswagen");
        MANUFACTURERS.put("YB1","Volvo Trucks");
        MANUFACTURERS.put("YCM","Mazda");
        MANUFACTURERS.put("YE2","Van Hool (buses)");
        MANUFACTURERS.put("YH2","BRP (Lynx snowmobiles)");
        MANUFACTURERS.put("YK1","Saab-Valmet");
        MANUFACTURERS.put("YS2","Scania AB");
        MANUFACTURERS.put("YS3","Saab");
        MANUFACTURERS.put("YS4","Scania Bus");
        MANUFACTURERS.put("YTN","Saab NEVS");
        MANUFACTURERS.put("YT9","Koenigsegg");
        MANUFACTURERS.put("007","Koenigsegg");
        MANUFACTURERS.put("034","Carvia");
        MANUFACTURERS.put("YU7","Husaberg (motorcycles)");
        MANUFACTURERS.put("YV1","Volvo Cars");
        MANUFACTURERS.put("YV4","Volvo Cars");
        MANUFACTURERS.put("YV2","Volvo Trucks");
        MANUFACTURERS.put("YV3","Volvo Buses");
        MANUFACTURERS.put("Y3M","MAZ");
        MANUFACTURERS.put("Y6D","Zaporozhets/AvtoZAZ");
        MANUFACTURERS.put("ZAA","Autobianchi");
        MANUFACTURERS.put("ZAM","Maserati");
        MANUFACTURERS.put("ZAP","Piaggio/Vespa/Gilera");
        MANUFACTURERS.put("ZAR","Alfa Romeo");
        MANUFACTURERS.put("ZBN","Benelli");
        MANUFACTURERS.put("ZCG","Cagiva SpA / MV Agusta");
        MANUFACTURERS.put("ZCF","Iveco");
        MANUFACTURERS.put("ZDM","Ducati Motor Holdings SpA");
        MANUFACTURERS.put("ZDF","Ferrari Dino");
        MANUFACTURERS.put("ZD0","Yamaha");
        MANUFACTURERS.put("ZD3","Beta Motor");
        MANUFACTURERS.put("ZD4","Aprilia");
        MANUFACTURERS.put("ZFA","Fiat");
        MANUFACTURERS.put("ZFC","Fiat V.I.");
        MANUFACTURERS.put("ZFF","Ferrari");
        MANUFACTURERS.put("ZGU","Moto Guzzi");
        MANUFACTURERS.put("ZHW","Lamborghini");
        MANUFACTURERS.put("ZJM","Malaguti");
        MANUFACTURERS.put("ZJN","Innocenti");
        MANUFACTURERS.put("ZKH","Husqvarna Motorcycles");
        MANUFACTURERS.put("ZLA","Lancia");
        MANUFACTURERS.put("ZOM","OM");
        MANUFACTURERS.put("Z8M","Marussia");
        MANUFACTURERS.put("1B3","Dodge");
        MANUFACTURERS.put("1C3","Chrysler");
        MANUFACTURERS.put("1C4","Chrysler");
        MANUFACTURERS.put("1C6","Chrysler");
        MANUFACTURERS.put("1D3","Dodge");
        MANUFACTURERS.put("1FA","Ford Motor Company");
        MANUFACTURERS.put("1FB","Ford Motor Company");
        MANUFACTURERS.put("1FC","Ford Motor Company");
        MANUFACTURERS.put("1FD","Ford Motor Company");
        MANUFACTURERS.put("1FM","Ford Motor Company");
        MANUFACTURERS.put("1FT","Ford Motor Company");
        MANUFACTURERS.put("1FU","Freightliner");
        MANUFACTURERS.put("1FV","Freightliner");
        MANUFACTURERS.put("1F9","FWD Corp.");
        MANUFACTURERS.put("1G","General Motors");
        MANUFACTURERS.put("1GC","Chevrolet Truck");
        MANUFACTURERS.put("1GT","GMC Truck");
        MANUFACTURERS.put("1G1","Chevrolet");
        MANUFACTURERS.put("1G2","Pontiac");
        MANUFACTURERS.put("1G3","Oldsmobile");
        MANUFACTURERS.put("1G4","Buick");
        MANUFACTURERS.put("1G6","Cadillac");
        MANUFACTURERS.put("1G8","Saturn");
        MANUFACTURERS.put("1GM","Pontiac");
        MANUFACTURERS.put("1GY","Cadillac");
        MANUFACTURERS.put("1H","Honda");
        MANUFACTURERS.put("1HD","Harley-Davidson");
        MANUFACTURERS.put("1J4","Jeep");
        MANUFACTURERS.put("1J8","Jeep");
        MANUFACTURERS.put("1L","Lincoln");
        MANUFACTURERS.put("1ME","Mercury");
        MANUFACTURERS.put("1M1","Mack Truck");
        MANUFACTURERS.put("1M2","Mack Truck");
        MANUFACTURERS.put("1M3","Mack Truck");
        MANUFACTURERS.put("1M4","Mack Truck");
        MANUFACTURERS.put("1M9","Mynatt Truck & Equipment");
        MANUFACTURERS.put("1N","Nissan");
        MANUFACTURERS.put("1NX","NUMMI");
        MANUFACTURERS.put("1P3","Plymouth");
        MANUFACTURERS.put("1R9","Roadrunner Hay Squeeze");
        MANUFACTURERS.put("1VW","Volkswagen");
        MANUFACTURERS.put("1XK","Kenworth");
        MANUFACTURERS.put("1XP","Peterbilt");
        MANUFACTURERS.put("1YV","Mazda (AutoAlliance International)");
        MANUFACTURERS.put("1ZV","Ford (AutoAlliance International)");
        MANUFACTURERS.put("2A4","Chrysler");
        MANUFACTURERS.put("2BP","Bombardier Recreational Products");
        MANUFACTURERS.put("2B3","Dodge");
        MANUFACTURERS.put("2B7","Dodge");
        MANUFACTURERS.put("2C3","Chrysler");
        MANUFACTURERS.put("2CN","CAMI");
        MANUFACTURERS.put("2D3","Dodge");
        MANUFACTURERS.put("2FA","Ford Motor Company");
        MANUFACTURERS.put("2FB","Ford Motor Company");
        MANUFACTURERS.put("2FC","Ford Motor Company");
        MANUFACTURERS.put("2FM","Ford Motor Company");
        MANUFACTURERS.put("2FT","Ford Motor Company");
        MANUFACTURERS.put("2FU","Freightliner");
        MANUFACTURERS.put("2FV","Freightliner");
        MANUFACTURERS.put("2FZ","Sterling");
        MANUFACTURERS.put("2Gx","General Motors");
        MANUFACTURERS.put("2G1","Chevrolet");
        MANUFACTURERS.put("2G2","Pontiac");
        MANUFACTURERS.put("2G3","Oldsmobile");
        MANUFACTURERS.put("2G4","Buick");
        MANUFACTURERS.put("2G9","Gnome Homes");
        MANUFACTURERS.put("2HG","Honda");
        MANUFACTURERS.put("2HK","Honda");
        MANUFACTURERS.put("2HJ","Honda");
        MANUFACTURERS.put("2HM","Hyundai");
        MANUFACTURERS.put("2M","Mercury");
        MANUFACTURERS.put("2NV","Nova Bus");
        MANUFACTURERS.put("2P3","Plymouth");
        MANUFACTURERS.put("2T","Toyota");
        MANUFACTURERS.put("2TP","Triple E LTD");
        MANUFACTURERS.put("2V4","Volkswagen");
        MANUFACTURERS.put("2V8","Volkswagen");
        MANUFACTURERS.put("2WK","Western Star");
        MANUFACTURERS.put("2WL","Western Star");
        MANUFACTURERS.put("2WM","Western Star");
        MANUFACTURERS.put("3C4","Chrysler");
        MANUFACTURERS.put("3D3","Dodge");
        MANUFACTURERS.put("3D4","Dodge");
        MANUFACTURERS.put("3FA","Ford Motor Company");
        MANUFACTURERS.put("3FE","Ford Motor Company");
        MANUFACTURERS.put("3G","General Motors");
        MANUFACTURERS.put("3H","Honda");
        MANUFACTURERS.put("3JB","BRP (all-terrain vehicles)");
        MANUFACTURERS.put("3MD","Mazda");
        MANUFACTURERS.put("3MZ","Mazda");
        MANUFACTURERS.put("3N","Nissan");
        MANUFACTURERS.put("3P3","Plymouth");
        MANUFACTURERS.put("3VW","Volkswagen");
        MANUFACTURERS.put("4F","Mazda");
        MANUFACTURERS.put("4JG","Mercedes-Benz");
        MANUFACTURERS.put("4M","Mercury");
        MANUFACTURERS.put("4RK","Nova Bus");
        MANUFACTURERS.put("4S","Subaru-Isuzu Automotive");
        MANUFACTURERS.put("4T","Toyota");
        MANUFACTURERS.put("4T9","Lumen Motors");
        MANUFACTURERS.put("4UF","Arctic Cat Inc.");
        MANUFACTURERS.put("4US","BMW");
        MANUFACTURERS.put("4UZ","Frt-Thomas Bus");
        MANUFACTURERS.put("4V1","Volvo");
        MANUFACTURERS.put("4V2","Volvo");
        MANUFACTURERS.put("4V3","Volvo");
        MANUFACTURERS.put("4V4","Volvo");
        MANUFACTURERS.put("4V5","Volvo");
        MANUFACTURERS.put("4V6","Volvo");
        MANUFACTURERS.put("4VL","Volvo");
        MANUFACTURERS.put("4VM","Volvo");
        MANUFACTURERS.put("4VZ","Volvo");
        MANUFACTURERS.put("538","Zero Motorcycles");
        MANUFACTURERS.put("5F","Honda Alabama");
        MANUFACTURERS.put("5J","Honda Ohio");
        MANUFACTURERS.put("5L","Lincoln");
        MANUFACTURERS.put("5N1","Nissan");
        MANUFACTURERS.put("5NP","Hyundai");
        MANUFACTURERS.put("5T","Toyota - trucks");
        MANUFACTURERS.put("5YJ","Tesla, Inc.");
        MANUFACTURERS.put("6AB","MAN");
        MANUFACTURERS.put("6F4","Nissan Motor Company");
        MANUFACTURERS.put("6F5","Kenworth");
        MANUFACTURERS.put("6FP","Ford Motor Company");
        MANUFACTURERS.put("6G1","General Motors-Holden (post Nov 2002)");
        MANUFACTURERS.put("6G2","Pontiac (GTO & G8)");
        MANUFACTURERS.put("6H8","General Motors-Holden (pre Nov 2002)");
        MANUFACTURERS.put("6MM","Mitsubishi Motors");
        MANUFACTURERS.put("6T1","Toyota Motor Corporation");
        MANUFACTURERS.put("6U9","Privately Imported car");
        MANUFACTURERS.put("8AD","Peugeot");
        MANUFACTURERS.put("8AF","Ford Motor Company");
        MANUFACTURERS.put("8AG","Chevrolet");
        MANUFACTURERS.put("8AJ","Toyota");
        MANUFACTURERS.put("8AK","Suzuki");
        MANUFACTURERS.put("8AP","Fiat");
        MANUFACTURERS.put("8AW","Volkswagen");
        MANUFACTURERS.put("8A1","Renault");
        MANUFACTURERS.put("8GD","Peugeot");
        MANUFACTURERS.put("8GG","Chevrolet");
        MANUFACTURERS.put("935","Citroën");
        MANUFACTURERS.put("936","Peugeot");
        MANUFACTURERS.put("93H","Honda");
        MANUFACTURERS.put("93R","Toyota");
        MANUFACTURERS.put("93U","Audi");
        MANUFACTURERS.put("93V","Audi");
        MANUFACTURERS.put("93X","Mitsubishi Motors");
        MANUFACTURERS.put("93Y","Renault");
        MANUFACTURERS.put("94D","Nissan");
        MANUFACTURERS.put("9BD","Fiat");
        MANUFACTURERS.put("9BF","Ford Motor Company");
        MANUFACTURERS.put("9BG","Chevrolet");
        MANUFACTURERS.put("9BM","Mercedes-Benz");
        MANUFACTURERS.put("9BR","Toyota");
        MANUFACTURERS.put("9BS","Scania");
        MANUFACTURERS.put("9BW","Volkswagen");
        MANUFACTURERS.put("9FB","Renault");
        MANUFACTURERS.put("WB1","BMW Motorrad of North America");
        MANUFACTURERS.put("W1K","Mercedes");
        MANUFACTURERS.put("W1V","Mercedes");
        MANUFACTURERS.put("W1N","Mercedes");
        MANUFACTURERS.put("WAP","BMW");
        MANUFACTURERS.put("YAR","Toyota");
    }
}
